apiVersion: v1
kind: Namespace
metadata: 
  name: quiz8

---
apiVersion: v1
kind: ServiceAccount
metadata: 
  name: testuser 
--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: 
  namespace: quiz8
  name: test-service
rules: 
- apiGroups: ["apps"]
  resources: ["service"]
  verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: 
  namespace: quiz8
  name: testrolebinding
subjects:
- kind: ServiceAccount
  name: testuser 
  namespace: quiz8
roleRef:
  kind: Role
  name: test-service 
  apiGroup: rbac.authorization.k8s.io
