apiVersion: v1
kind: Namespace
metadata: 
  name: quiz2

---
apiVersion: v1
kind: Pod
metadata: 
  namespace: quiz2
  name: container-env-example
spec: 
  containers: 
  - name: my-container
    image: busybox
    args: ['tail', '-f', '/dev/null']
    envFrom:
    - configMapRef: 
        name: start-k8s

---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: quiz2 
  name: start-k8s
data: 
  container: docker
  k8s: kubernetes

