apiVersion: v1
kind: Namespace
metadata: 
  name: quiz4

---
apiVersion: v1
kind: ConfigMap
metadata: 
  namespace: metallb-system
  name: config
data: 
  config: |
    address-pools: 
    - name: default 
      protocol: layer2
      addresses:
      - 211.183.3.201-211.183.3.239

---
apiVersion: apps/v1
kind: Deployment
metadata: 
  namespace: quiz4
  name: nginx
spec: 
  replicas: 3
  selector: 
    matchLabels: 
      app: nginx
  template: 
    metadata: 
      labels: 
        app: nginx
    spec: 
      containers: 
      - name: nginx
        image: nginx:1.10
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata: 
  namespace: quiz4
  name: nginx
  labels: 
    app: nginx
spec: 
  externalTrafficPolicy: Local
  ports: 
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector: 
    app: nginx
  type: LoadBalancer #0
