apiVersion: v1
kind: Namespace
metadata: 
  name: quiz3
---
apiVersion: apps/v1 
kind: Deployment
metadata: 
  namespace: quiz3
  name: test-deploy
spec: 
  replicas: 3
  selector:  
    matchLabels: 
      app: webserver
  template: 
    metadata: 
      name: my-webserver
      labels: 
        app: webserver
    spec: 
      containers:
      - name: my-webserver
        image: nginx:1.10 #d
        ports:
        - containerPort: 80 
--- 
apiVersion: v1
kind: Service
metadata:
  namespace: quiz3
  name: webserver-nodeport
spec:
  selector:
    app: webserver
  ports:
  - name: web-port
    port: 8080
    targetPort: 80
  type: NodePort

